defaults:
  -
    scope:
      path: ""
    values:
      layout: "content"
encoding: 'utf-8'
collections:
  pages:
    output: true
    permalink: /:name
  docs:
    output: true
    permalink: /docs/:name
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge